{% set name = "nerval" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 195f15e7294ca565537729468493fac15afbfe8ba63aa2dfedf29123bb3010dc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pandas
    - numpy
    - matplotlib-base
    - scikit-learn
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nerval

about:
  home: https://github.com/mdadda/nerval
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: Entity-level confusion matrix and classification report to evaluate Named Entity Recognition (NER) models.
  doc_url:
  dev_url: https://github.com/mdadda/nerval

extra:
  recipe-maintainers:
    - mdadda
